apiVersion: skaffold/v2beta1
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: navalta3030/react-client
    docker:
      dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
      - react-client-chart/templates/react-*