apiVersion: v1
kind: Service
metadata:
  name: react-client
spec:
  type: NodePort
  selector:
    component: web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000


# apiVersion: v1
# kind: Service
# metadata:
#   name: react-client
# spec:
#   type: ClusterIP
#   selector:
#     component: web
#   ports:
#     - port: 3000
#       targetPort: 3000